import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/NavBar/Header";

const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight: ['500', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      
      <body className={montserrat.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
